on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - elm-worker/**
      - .github/workflows/elm-worker.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - uses: jorelali/setup-elm@v4
        with:
          elm-version: 0.19.1

      - run: |
          elm make --optimize --output=app/EasyRacer.js src/EasyRacer.elm
          npm install --no-fund xhr2
          npm install -g --save-dev --no-fund jest
          npm install --save-dev --no-fund testcontainers
          npm test
        working-directory: ./elm-worker
