on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - javascript-stdlib/**
      - .github/workflows/javascript-stdlib.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - run: npm test
        working-directory: ./javascript-stdlib
