on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          cache: 'pip'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: pytest
        working-directory: ./python-aiohttp
