on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - swift-async/**
      - .github/workflows/swift-async.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.5

      - run: swift -version

      - run: swift test -c release
        working-directory: ./swift-async
