on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - swift-async/**
      - .github/workflows/swift-async.yaml

jobs:
  test-linux:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - uses: sersoft-gmbh/swifty-linux-action@v1
        with:
          release-version: 5.6.1

      - run: swift test -c release
        working-directory: ./swift-async

  test-macos:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - run: ulimit -a

      - run: swift test -c release
        working-directory: ./swift-async
